- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3, virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando dependencias com pip (Django e Django REST)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Verificando se o projeto ja existe
      stat:
        path: /home/ubuntu/tcc/setup/settings.py
      register: projeto
    - name: Iniciando projeto django
      shell: ". /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/"
      when: not projeto.stat.exists
    - name: Alterando allowed_hosts do settings.py
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regex: 'ALLOWED_HOSTS' 
        line: 'ALLOWED_HOSTS=["*"]'
        backrefs: yes
    - name: Criando arquivo de start e clear do servidor
      shell: "cd /home/ubuntu/tcc; echo python3 manage.py runserver 0.0.0.0:8000 >> start.sh; echo rm -rf db.sqlite3 start.sh manage.py setup remove.sh >> clear.sh;sudo chmod u=rwx,g=rx,o=rx ./*.sh"